
project_id = "xvjgziihekwjyzihjihx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[functions]
[functions.populate-italian-locations]
verify_jwt = false
