import { MaterialityIssue } from '../types';

const createBaseIssue = (id: string, name: string, description: string): MaterialityIssue => ({
  id,
  name,
  description,
  impactRelevance: 50,
  financialRelevance: 50,
  isMaterial: true,
  stakeholderRelevance: undefined,
  iroSelections: undefined
});

export const predefinedIssues: MaterialityIssue[] = [
  createBaseIssue('climate-adaptation', 'Adattamento ai cambiamenti climatici', 'Strategie e misure per adattarsi ai cambiamenti climatici'),
  createBaseIssue('climate-mitigation', 'Mitigazione dei cambiamenti climatici', 'Riduzione delle emissioni di gas serra e altri interventi per mitigare i cambiamenti climatici'),
  createBaseIssue('energy', 'Energia', 'Uso e gestione dell\'energia, inclusa efficienza energetica e fonti rinnovabili'),
  
  createBaseIssue('pollution-air', 'Inquinamento dell\'aria', 'Emissioni in atmosfera e impatti sulla qualità dell\'aria'),
  createBaseIssue('pollution-water', 'Inquinamento dell\'acqua', 'Scarichi idrici e impatti sulla qualità dell\'acqua'),
  createBaseIssue('pollution-soil', 'Inquinamento del suolo', 'Contaminazione del suolo e impatti sulla qualità del terreno'),
  createBaseIssue('pollution-organisms', 'Inquinamento di organismi viventi e risorse alimentari', 'Impatti dell\'inquinamento sugli organismi viventi e sulla catena alimentare'),
  createBaseIssue('substances-concern', 'Sostanze preoccupanti', 'Gestione e riduzione delle sostanze preoccupanti nei processi produttivi e nei prodotti'),
  createBaseIssue('substances-extreme-concern', 'Sostanze estremamente preoccupanti', 'Gestione e eliminazione delle sostanze estremamente preoccupanti (SVHC)'),
  
  createBaseIssue('water-consumption', 'Consumo idrico', 'Utilizzo e consumo di risorse idriche'),
  createBaseIssue('water-withdrawal', 'Prelievi idrici', 'Prelievo di acqua da diverse fonti'),
  createBaseIssue('water-discharge', 'Scarichi di acque', 'Gestione degli scarichi idrici e del loro impatto ambientale'),
  createBaseIssue('ocean-discharge', 'Scarichi di acque negli oceani', 'Impatti degli scarichi idrici sugli ecosistemi marini'),
  createBaseIssue('marine-resources', 'Estrazione e uso di risorse marine', 'Utilizzo sostenibile delle risorse marine'),
  
  createBaseIssue('biodiversity-climate', 'Biodiversità: Cambiamenti climatici', 'Impatti dei cambiamenti climatici sulla biodiversità'),
  createBaseIssue('biodiversity-land-use', 'Biodiversità: Cambiamento di uso del suolo e dell\'acqua', 'Impatti del cambiamento di uso del suolo, dell\'acqua dolce e del mare sulla biodiversità'),
  createBaseIssue('biodiversity-exploitation', 'Biodiversità: Sfruttamento diretto', 'Impatti dello sfruttamento diretto delle risorse naturali sulla biodiversità'),
  createBaseIssue('biodiversity-invasive', 'Biodiversità: Specie esotiche invasive', 'Impatti delle specie esotiche invasive sugli ecosistemi locali'),
  createBaseIssue('biodiversity-pollution', 'Biodiversità: Inquinamento', 'Impatti dell\'inquinamento sulla biodiversità'),
  createBaseIssue('biodiversity-other', 'Biodiversità: Altri fattori di impatto', 'Altri fattori che impattano direttamente sulla biodiversità'),
  createBaseIssue('species-population', 'Dimensioni della popolazione di una specie', 'Impatti sulle dimensioni delle popolazioni di specie'),
  createBaseIssue('species-extinction', 'Rischio di estinzione globale di una specie', 'Contributo al rischio di estinzione globale di specie'),
  createBaseIssue('soil-degradation', 'Degrado del suolo', 'Processi di degrado del suolo e misure di mitigazione'),
  createBaseIssue('desertification', 'Desertificazione', 'Processi di desertificazione e misure di contrasto'),
  createBaseIssue('soil-sealing', 'Impermeabilizzazione del suolo', 'Impatti dell\'impermeabilizzazione del suolo e misure di mitigazione'),
  createBaseIssue('ecosystem-services', 'Servizi ecosistemici', 'Impatti e dipendenze in termini di servizi ecosistemici'),
  
  createBaseIssue('resource-inflows', 'Afflussi di risorse', 'Gestione degli afflussi di risorse, compreso l\'uso efficiente delle risorse'),
  createBaseIssue('resource-outflows', 'Deflussi di risorse', 'Gestione dei deflussi di risorse connessi a prodotti e servizi'),
  createBaseIssue('waste', 'Rifiuti', 'Gestione dei rifiuti e strategie di riduzione'),
  
  createBaseIssue('labor-secure', 'Occupazione sicura', 'Garantire condizioni di occupazione sicura e stabile per i lavoratori'),
  createBaseIssue('labor-hours', 'Orario di lavoro', 'Gestione dell\'orario di lavoro e rispetto dei limiti previsti'),
  createBaseIssue('labor-wages', 'Salari adeguati', 'Garantire salari adeguati e dignitosi ai lavoratori'),
  createBaseIssue('labor-social-dialogue', 'Dialogo sociale', 'Promozione del dialogo tra lavoratori, rappresentanti e azienda'),
  createBaseIssue('labor-association', 'Libertà di associazione e diritti di informazione', 'Garantire la libertà di associazione, l\'esistenza di comitati aziendali e i diritti di informazione, consultazione e partecipazione dei lavoratori'),
  createBaseIssue('labor-collective', 'Contrattazione collettiva', 'Garantire il diritto alla contrattazione collettiva, inclusa la percentuale di lavoratori coperti da contratti collettivi'),
  createBaseIssue('labor-work-life', 'Equilibrio tra vita professionale e vita privata', 'Politiche per favorire l\'equilibrio tra vita professionale e vita privata'),
  createBaseIssue('labor-safety', 'Salute e sicurezza sul lavoro', 'Protezione della salute e sicurezza dei lavoratori'),
  createBaseIssue('labor-gender', 'Parità di genere e retribuzione', 'Garantire la parità di genere e la parità di retribuzione per un lavoro di pari valore'),
  createBaseIssue('labor-training', 'Formazione e sviluppo delle competenze', 'Investimenti nella formazione e nello sviluppo delle competenze dei lavoratori'),
  createBaseIssue('labor-disability', 'Occupazione e inclusione delle persone con disabilità', 'Politiche per l\'inclusione lavorativa delle persone con disabilità'),
  createBaseIssue('labor-harassment', 'Misure contro la violenza e le molestie', 'Misure contro la violenza e le molestie sul luogo di lavoro'),
  createBaseIssue('labor-diversity', 'Diversità', 'Promozione della diversità nella forza lavoro'),
  createBaseIssue('labor-child', 'Lavoro minorile', 'Prevenzione e contrasto del lavoro minorile'),
  createBaseIssue('labor-forced', 'Lavoro forzato', 'Prevenzione e contrasto del lavoro forzato'),
  createBaseIssue('labor-housing', 'Alloggi adeguati', 'Garantire alloggi adeguati ai lavoratori, ove applicabile'),
  createBaseIssue('labor-privacy', 'Riservatezza', 'Tutela della riservatezza dei dati dei lavoratori'),
  
  createBaseIssue('supply-labor-secure', 'Occupazione sicura nella catena del valore', 'Garantire condizioni di occupazione sicura per i lavoratori nella catena di fornitura'),
  createBaseIssue('supply-labor-hours', 'Orario di lavoro nella catena del valore', 'Monitoraggio dell\'orario di lavoro nella catena di fornitura'),
  createBaseIssue('supply-labor-wages', 'Salari adeguati nella catena del valore', 'Garantire salari adeguati ai lavoratori nella catena di fornitura'),
  createBaseIssue('supply-labor-dialogue', 'Dialogo sociale nella catena del valore', 'Promozione del dialogo sociale nella catena di fornitura'),
  createBaseIssue('supply-labor-association', 'Libertà di associazione nella catena del valore', 'Garantire la libertà di associazione, compresa l\'esistenza di comitati aziendali nella catena di fornitura'),
  createBaseIssue('supply-labor-collective', 'Contrattazione collettiva nella catena del valore', 'Rispetto della contrattazione collettiva nella catena di fornitura'),
  createBaseIssue('supply-labor-work-life', 'Equilibrio vita-lavoro nella catena del valore', 'Equilibrio tra vita professionale e vita privata nella catena di fornitura'),
  createBaseIssue('supply-labor-safety', 'Salute e sicurezza nella catena del valore', 'Salute e sicurezza dei lavoratori nella catena di fornitura'),
  createBaseIssue('supply-labor-gender', 'Parità di genere nella catena del valore', 'Parità di genere e di retribuzione nella catena di fornitura'),
  createBaseIssue('supply-labor-training', 'Formazione nella catena del valore', 'Formazione e sviluppo delle competenze nella catena di fornitura'),
  createBaseIssue('supply-labor-disability', 'Inclusione disabilità nella catena del valore', 'Occupazione e inclusione delle persone con disabilità nella catena di fornitura'),
  createBaseIssue('supply-labor-harassment', 'Anti-molestie nella catena del valore', 'Misure contro la violenza e le molestie sul luogo di lavoro nella catena di fornitura'),
  createBaseIssue('supply-labor-diversity', 'Diversità nella catena del valore', 'Promozione della diversità nella catena di fornitura'),
  createBaseIssue('supply-labor-child', 'Lavoro minorile nella catena del valore', 'Prevenzione del lavoro minorile nella catena di fornitura'),
  createBaseIssue('supply-labor-forced', 'Lavoro forzato nella catena del valore', 'Prevenzione del lavoro forzato nella catena di fornitura'),
  createBaseIssue('supply-labor-housing', 'Alloggi nella catena del valore', 'Alloggi adeguati nella catena di fornitura'),
  createBaseIssue('supply-water-sanitation', 'Acqua e servizi igienico-sanitari', 'Accesso all\'acqua e ai servizi igienico-sanitari nella catena di fornitura'),
  createBaseIssue('supply-labor-privacy', 'Riservatezza nella catena del valore', 'Tutela della riservatezza nella catena di fornitura'),
  
  createBaseIssue('community-housing', 'Alloggi adeguati per le comunità', 'Garantire alloggi adeguati per le comunità locali'),
  createBaseIssue('community-food', 'Alimentazione adeguata', 'Garantire alimentazione adeguata per le comunità locali'),
  createBaseIssue('community-water', 'Acqua e servizi igienico-sanitari per le comunità', 'Garantire accesso ad acqua e servizi igienico-sanitari per le comunità locali'),
  createBaseIssue('community-land', 'Impatti legati al territorio', 'Gestione degli impatti legati al territorio sulle comunità locali'),
  createBaseIssue('community-security', 'Impatti legati alla sicurezza', 'Gestione degli impatti legati alla sicurezza sulle comunità locali'),
  createBaseIssue('community-expression', 'Libertà di espressione', 'Rispetto della libertà di espressione delle comunità'),
  createBaseIssue('community-association', 'Libertà di associazione delle comunità', 'Rispetto della libertà di associazione delle comunità'),
  createBaseIssue('community-rights-defenders', 'Impatto sui difensori dei diritti umani', 'Gestione dell\'impatto sui difensori dei diritti umani'),
  createBaseIssue('indigenous-consent', 'Consenso libero, previo e informato', 'Rispetto del consenso libero, previo e informato dei popoli indigeni'),
  createBaseIssue('indigenous-determination', 'Autodeterminazione', 'Rispetto dell\'autodeterminazione dei popoli indigeni'),
  createBaseIssue('indigenous-cultural', 'Diritti culturali dei popoli indigeni', 'Rispetto dei diritti culturali dei popoli indigeni'),
  
  createBaseIssue('consumer-privacy', 'Riservatezza dei consumatori', 'Tutela della riservatezza dei dati dei consumatori'),
  createBaseIssue('consumer-expression', 'Libertà di espressione dei consumatori', 'Rispetto della libertà di espressione dei consumatori'),
  createBaseIssue('consumer-information', 'Accesso a informazioni di qualità', 'Garantire ai consumatori l\'accesso a informazioni di qualità'),
  createBaseIssue('consumer-health-safety', 'Salute e sicurezza dei consumatori', 'Tutela della salute e sicurezza dei consumatori'),
  createBaseIssue('consumer-security', 'Sicurezza della persona', 'Tutela della sicurezza personale dei consumatori'),
  createBaseIssue('consumer-child-protection', 'Protezione dei bambini', 'Misure per la protezione dei bambini consumatori'),
  createBaseIssue('consumer-non-discrimination', 'Non discriminazione dei consumatori', 'Prevenzione della discriminazione nei confronti dei consumatori'),
  createBaseIssue('consumer-access', 'Accesso a prodotti e servizi', 'Garantire l\'accesso equo a prodotti e servizi'),
  createBaseIssue('consumer-practices', 'Pratiche commerciali responsabili', 'Adozione di pratiche commerciali responsabili verso i consumatori'),
  
  createBaseIssue('business-culture', 'Cultura d\'impresa', 'Promozione di una cultura d\'impresa etica e responsabile'),
  createBaseIssue('whistleblower-protection', 'Protezione degli informatori', 'Misure per la protezione degli informatori (whistleblower)'),
  createBaseIssue('animal-welfare', 'Benessere degli animali', 'Protezione del benessere degli animali'),
  createBaseIssue('political-engagement', 'Impegno politico e attività di lobbying', 'Gestione responsabile dell\'impegno politico e delle attività di lobbying'),
  createBaseIssue('supplier-relations', 'Gestione dei rapporti con i fornitori', 'Gestione dei rapporti con i fornitori, comprese le prassi di pagamento'),
  createBaseIssue('corruption-prevention', 'Prevenzione della corruzione', 'Prevenzione e individuazione della corruzione, compresa la formazione'),
  createBaseIssue('corruption-incidents', 'Incidenti di corruzione', 'Gestione degli incidenti di corruzione')
];

export const esrsThemes = [
  "Cambiamenti climatici",
  "Inquinamento",
  "Acque e risorse marine",
  "Biodiversità ed ecosistemi",
  "Economia circolare",
  "Forza lavoro propria",
  "Lavoratori nella catena del valore",
  "Comunità interessate",
  "Consumatori e utilizzatori finali",
  "Condotta delle imprese"
];
